// GENERATED CODE — DO NOT MODIFY BY HAND
//
// Generated by dart_open_fetch v0.1.0
// Timestamp: 2026-02-17T03:40:28.495573Z
// Source: packages/dart_open_fetch_core/test/fixtures/petstore.yaml
//
// requires: dart_open_fetch_runtime ^0.1.0

import 'dart:convert';

import 'package:dart_open_fetch_runtime/dart_open_fetch_runtime.dart';

import '../models.dart';

class PetClient {
  PetClient({
    required HttpAdapter adapter,
    List<Middleware> middleware = const [],
    this.baseUrl = 'https://petstore3.swagger.io/api/v3',
  }) : _chain = MiddlewareChain(adapter, middleware);

  final MiddlewareChain _chain;
  final String baseUrl;

  Future<ApiResponse<Pet>> addPet({
    required Pet body,
  }) async {
    final basePath = baseUrl.endsWith('/')
        ? baseUrl.substring(0, baseUrl.length - 1)
        : baseUrl;
    final url = Uri.parse('$basePath/pet');
    final headers = <String, String>{
      'Content-Type': 'application/json',
    };
    final jsonBody = jsonEncode(body.toJson());
    final request = HttpRequest(
      method: 'POST',
      url: url,
      headers: headers,
      body: jsonBody,
    );

    final response = await _chain.send(request);
    if (response.statusCode >= 200 && response.statusCode < 300) {
      if (response.body.isEmpty) {
        throw ApiException(
          statusCode: response.statusCode,
          body: 'Empty response body',
          headers: response.headers,
        );
      }
      final json = jsonDecode(response.body);
      return ApiResponse(
        data: Pet.fromJson(json as Map<String, dynamic>),
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    throw ApiException(
      statusCode: response.statusCode,
      body: response.body,
      headers: response.headers,
    );
  }

  Future<ApiResponse<Pet>> updatePet({
    required Pet body,
  }) async {
    final basePath = baseUrl.endsWith('/')
        ? baseUrl.substring(0, baseUrl.length - 1)
        : baseUrl;
    final url = Uri.parse('$basePath/pet');
    final headers = <String, String>{
      'Content-Type': 'application/json',
    };
    final jsonBody = jsonEncode(body.toJson());
    final request = HttpRequest(
      method: 'PUT',
      url: url,
      headers: headers,
      body: jsonBody,
    );

    final response = await _chain.send(request);
    if (response.statusCode >= 200 && response.statusCode < 300) {
      if (response.body.isEmpty) {
        throw ApiException(
          statusCode: response.statusCode,
          body: 'Empty response body',
          headers: response.headers,
        );
      }
      final json = jsonDecode(response.body);
      return ApiResponse(
        data: Pet.fromJson(json as Map<String, dynamic>),
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    throw ApiException(
      statusCode: response.statusCode,
      body: response.body,
      headers: response.headers,
    );
  }

  Future<ApiResponse<List<Pet>>> findPetsByStatus({
    required String status,
  }) async {
    final basePath = baseUrl.endsWith('/')
        ? baseUrl.substring(0, baseUrl.length - 1)
        : baseUrl;
    final queryParams = <String, List<String>>{};
    queryParams['status'] = [status.toString()];
    final url = Uri.parse('$basePath/pet/findByStatus').replace(
      queryParameters: queryParams,
    );
    final headers = <String, String>{};
    final request = HttpRequest(
      method: 'GET',
      url: url,
      headers: headers,
    );

    final response = await _chain.send(request);
    if (response.statusCode >= 200 && response.statusCode < 300) {
      if (response.body.isEmpty) {
        throw ApiException(
          statusCode: response.statusCode,
          body: 'Empty response body',
          headers: response.headers,
        );
      }
      final json = jsonDecode(response.body);
      return ApiResponse(
        data: (json as List<dynamic>)
            .map((e) => Pet.fromJson(e as Map<String, dynamic>))
            .toList(),
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    throw ApiException(
      statusCode: response.statusCode,
      body: response.body,
      headers: response.headers,
    );
  }

  Future<ApiResponse<List<Pet>>> findPetsByTags({
    required List<String> tags,
  }) async {
    final basePath = baseUrl.endsWith('/')
        ? baseUrl.substring(0, baseUrl.length - 1)
        : baseUrl;
    final queryParams = <String, List<String>>{};
    queryParams['tags'] = tags.map((v) => v.toString()).toList();
    final url = Uri.parse('$basePath/pet/findByTags').replace(
      queryParameters: queryParams,
    );
    final headers = <String, String>{};
    final request = HttpRequest(
      method: 'GET',
      url: url,
      headers: headers,
    );

    final response = await _chain.send(request);
    if (response.statusCode >= 200 && response.statusCode < 300) {
      if (response.body.isEmpty) {
        throw ApiException(
          statusCode: response.statusCode,
          body: 'Empty response body',
          headers: response.headers,
        );
      }
      final json = jsonDecode(response.body);
      return ApiResponse(
        data: (json as List<dynamic>)
            .map((e) => Pet.fromJson(e as Map<String, dynamic>))
            .toList(),
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    throw ApiException(
      statusCode: response.statusCode,
      body: response.body,
      headers: response.headers,
    );
  }

  Future<ApiResponse<Pet>> getPetById({
    required int petId,
  }) async {
    final basePath = baseUrl.endsWith('/')
        ? baseUrl.substring(0, baseUrl.length - 1)
        : baseUrl;
    final url =
        Uri.parse('$basePath/pet/${Uri.encodeComponent(petId.toString())}');
    final headers = <String, String>{};
    final request = HttpRequest(
      method: 'GET',
      url: url,
      headers: headers,
    );

    final response = await _chain.send(request);
    if (response.statusCode >= 200 && response.statusCode < 300) {
      if (response.body.isEmpty) {
        throw ApiException(
          statusCode: response.statusCode,
          body: 'Empty response body',
          headers: response.headers,
        );
      }
      final json = jsonDecode(response.body);
      return ApiResponse(
        data: Pet.fromJson(json as Map<String, dynamic>),
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    throw ApiException(
      statusCode: response.statusCode,
      body: response.body,
      headers: response.headers,
    );
  }

  Future<ApiResponse<Pet>> updatePetWithForm({
    required int petId,
    String? name,
    String? status,
  }) async {
    final basePath = baseUrl.endsWith('/')
        ? baseUrl.substring(0, baseUrl.length - 1)
        : baseUrl;
    final queryParams = <String, List<String>>{};
    if (name != null) {
      queryParams['name'] = [name.toString()];
    }
    if (status != null) {
      queryParams['status'] = [status.toString()];
    }
    final url =
        Uri.parse('$basePath/pet/${Uri.encodeComponent(petId.toString())}')
            .replace(
      queryParameters: queryParams,
    );
    final headers = <String, String>{};
    final request = HttpRequest(
      method: 'POST',
      url: url,
      headers: headers,
    );

    final response = await _chain.send(request);
    if (response.statusCode >= 200 && response.statusCode < 300) {
      if (response.body.isEmpty) {
        throw ApiException(
          statusCode: response.statusCode,
          body: 'Empty response body',
          headers: response.headers,
        );
      }
      final json = jsonDecode(response.body);
      return ApiResponse(
        data: Pet.fromJson(json as Map<String, dynamic>),
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    throw ApiException(
      statusCode: response.statusCode,
      body: response.body,
      headers: response.headers,
    );
  }

  Future<HttpResponse> deletePet({
    String? apiKey,
    required int petId,
  }) async {
    final basePath = baseUrl.endsWith('/')
        ? baseUrl.substring(0, baseUrl.length - 1)
        : baseUrl;
    final url =
        Uri.parse('$basePath/pet/${Uri.encodeComponent(petId.toString())}');
    final headers = <String, String>{};
    if (apiKey != null) {
      headers['api_key'] = apiKey.toString();
    }
    final request = HttpRequest(
      method: 'DELETE',
      url: url,
      headers: headers,
    );

    final response = await _chain.send(request);
    return response;
  }

  Future<ApiResponse<ApiResponse2>> uploadFile({
    required int petId,
    String? additionalMetadata,
    String? body,
  }) async {
    final basePath = baseUrl.endsWith('/')
        ? baseUrl.substring(0, baseUrl.length - 1)
        : baseUrl;
    final queryParams = <String, List<String>>{};
    if (additionalMetadata != null) {
      queryParams['additionalMetadata'] = [additionalMetadata.toString()];
    }
    final url = Uri.parse(
            '$basePath/pet/${Uri.encodeComponent(petId.toString())}/uploadImage')
        .replace(
      queryParameters: queryParams,
    );
    final headers = <String, String>{};
    final request = HttpRequest(
      method: 'POST',
      url: url,
      headers: headers,
      body: body,
    );

    final response = await _chain.send(request);
    if (response.statusCode >= 200 && response.statusCode < 300) {
      if (response.body.isEmpty) {
        throw ApiException(
          statusCode: response.statusCode,
          body: 'Empty response body',
          headers: response.headers,
        );
      }
      final json = jsonDecode(response.body);
      return ApiResponse(
        data: ApiResponse2.fromJson(json as Map<String, dynamic>),
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    throw ApiException(
      statusCode: response.statusCode,
      body: response.body,
      headers: response.headers,
    );
  }
}
