// GENERATED CODE — DO NOT MODIFY BY HAND
//
// Generated by dart_open_fetch v0.1.0
// Timestamp: 2026-02-17T03:40:28.518380Z
// Source: packages/dart_open_fetch_core/test/fixtures/petstore.yaml
//
// requires: dart_open_fetch_runtime ^0.1.0

import 'dart:convert';

import 'package:dart_open_fetch_runtime/dart_open_fetch_runtime.dart';

import '../models.dart';

class UserClient {
  UserClient({
    required HttpAdapter adapter,
    List<Middleware> middleware = const [],
    this.baseUrl = 'https://petstore3.swagger.io/api/v3',
  }) : _chain = MiddlewareChain(adapter, middleware);

  final MiddlewareChain _chain;
  final String baseUrl;

  Future<ApiResponse<User>> createUser({
    User? body,
  }) async {
    final basePath = baseUrl.endsWith('/')
        ? baseUrl.substring(0, baseUrl.length - 1)
        : baseUrl;
    final url = Uri.parse('$basePath/user');
    final headers = <String, String>{
      'Content-Type': 'application/json',
    };
    final jsonBody = body != null ? jsonEncode(body.toJson()) : null;
    final request = HttpRequest(
      method: 'POST',
      url: url,
      headers: headers,
      body: jsonBody,
    );

    final response = await _chain.send(request);
    if (response.statusCode >= 200 && response.statusCode < 300) {
      if (response.body.isEmpty) {
        throw ApiException(
          statusCode: response.statusCode,
          body: 'Empty response body',
          headers: response.headers,
        );
      }
      final json = jsonDecode(response.body);
      return ApiResponse(
        data: User.fromJson(json as Map<String, dynamic>),
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    throw ApiException(
      statusCode: response.statusCode,
      body: response.body,
      headers: response.headers,
    );
  }

  Future<ApiResponse<User>> createUsersWithListInput({
    List<User>? body,
  }) async {
    final basePath = baseUrl.endsWith('/')
        ? baseUrl.substring(0, baseUrl.length - 1)
        : baseUrl;
    final url = Uri.parse('$basePath/user/createWithList');
    final headers = <String, String>{
      'Content-Type': 'application/json',
    };
    final jsonBody = body != null ? jsonEncode(body) : null;
    final request = HttpRequest(
      method: 'POST',
      url: url,
      headers: headers,
      body: jsonBody,
    );

    final response = await _chain.send(request);
    if (response.statusCode >= 200 && response.statusCode < 300) {
      if (response.body.isEmpty) {
        throw ApiException(
          statusCode: response.statusCode,
          body: 'Empty response body',
          headers: response.headers,
        );
      }
      final json = jsonDecode(response.body);
      return ApiResponse(
        data: User.fromJson(json as Map<String, dynamic>),
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    throw ApiException(
      statusCode: response.statusCode,
      body: response.body,
      headers: response.headers,
    );
  }

  Future<ApiResponse<String>> loginUser({
    String? username,
    String? password,
  }) async {
    final basePath = baseUrl.endsWith('/')
        ? baseUrl.substring(0, baseUrl.length - 1)
        : baseUrl;
    final queryParams = <String, List<String>>{};
    if (username != null) {
      queryParams['username'] = [username.toString()];
    }
    if (password != null) {
      queryParams['password'] = [password.toString()];
    }
    final url = Uri.parse('$basePath/user/login').replace(
      queryParameters: queryParams,
    );
    final headers = <String, String>{};
    final request = HttpRequest(
      method: 'GET',
      url: url,
      headers: headers,
    );

    final response = await _chain.send(request);
    if (response.statusCode >= 200 && response.statusCode < 300) {
      if (response.body.isEmpty) {
        throw ApiException(
          statusCode: response.statusCode,
          body: 'Empty response body',
          headers: response.headers,
        );
      }
      final json = jsonDecode(response.body);
      return ApiResponse(
        data: json as String,
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    throw ApiException(
      statusCode: response.statusCode,
      body: response.body,
      headers: response.headers,
    );
  }

  Future<HttpResponse> logoutUser() async {
    final basePath = baseUrl.endsWith('/')
        ? baseUrl.substring(0, baseUrl.length - 1)
        : baseUrl;
    final url = Uri.parse('$basePath/user/logout');
    final headers = <String, String>{};
    final request = HttpRequest(
      method: 'GET',
      url: url,
      headers: headers,
    );

    final response = await _chain.send(request);
    return response;
  }

  Future<ApiResponse<User>> getUserByName({
    required String username,
  }) async {
    final basePath = baseUrl.endsWith('/')
        ? baseUrl.substring(0, baseUrl.length - 1)
        : baseUrl;
    final url =
        Uri.parse('$basePath/user/${Uri.encodeComponent(username.toString())}');
    final headers = <String, String>{};
    final request = HttpRequest(
      method: 'GET',
      url: url,
      headers: headers,
    );

    final response = await _chain.send(request);
    if (response.statusCode >= 200 && response.statusCode < 300) {
      if (response.body.isEmpty) {
        throw ApiException(
          statusCode: response.statusCode,
          body: 'Empty response body',
          headers: response.headers,
        );
      }
      final json = jsonDecode(response.body);
      return ApiResponse(
        data: User.fromJson(json as Map<String, dynamic>),
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    throw ApiException(
      statusCode: response.statusCode,
      body: response.body,
      headers: response.headers,
    );
  }

  Future<HttpResponse> updateUser({
    required String username,
    User? body,
  }) async {
    final basePath = baseUrl.endsWith('/')
        ? baseUrl.substring(0, baseUrl.length - 1)
        : baseUrl;
    final url =
        Uri.parse('$basePath/user/${Uri.encodeComponent(username.toString())}');
    final headers = <String, String>{
      'Content-Type': 'application/json',
    };
    final jsonBody = body != null ? jsonEncode(body.toJson()) : null;
    final request = HttpRequest(
      method: 'PUT',
      url: url,
      headers: headers,
      body: jsonBody,
    );

    final response = await _chain.send(request);
    return response;
  }

  Future<HttpResponse> deleteUser({
    required String username,
  }) async {
    final basePath = baseUrl.endsWith('/')
        ? baseUrl.substring(0, baseUrl.length - 1)
        : baseUrl;
    final url =
        Uri.parse('$basePath/user/${Uri.encodeComponent(username.toString())}');
    final headers = <String, String>{};
    final request = HttpRequest(
      method: 'DELETE',
      url: url,
      headers: headers,
    );

    final response = await _chain.send(request);
    return response;
  }
}
