name: dart_open_fetch_workspace

packages:
  - packages/*

scripts:
  analyze:
    description: Run dart analyze on all packages
    run: dart analyze --fatal-infos
    exec:
      concurrency: 1

  test:
    description: Run tests in all packages
    run: dart test
    exec:
      concurrency: 1
    packageFilters:
      dirExists: test

  format-check:
    description: Check formatting of all packages
    run: dart format --set-exit-if-changed .
    exec:
      concurrency: 1
