// GENERATED CODE — DO NOT MODIFY BY HAND
//
// Generated by dart_open_fetch v0.1.0
// Timestamp: 2026-02-17T03:40:28.461003Z
// Source: packages/dart_open_fetch_core/test/fixtures/petstore.yaml
//
// requires: dart_open_fetch_runtime ^0.1.0

bool _deepEquals(dynamic a, dynamic b) {
  if (identical(a, b)) return true;
  if (a is List && b is List) {
    if (a.length != b.length) return false;
    for (var i = 0; i < a.length; i++) {
      if (!_deepEquals(a[i], b[i])) return false;
    }
    return true;
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) return false;
    for (final key in a.keys) {
      if (!b.containsKey(key) || !_deepEquals(a[key], b[key])) return false;
    }
    return true;
  }
  return a == b;
}

int _deepHash(dynamic value) {
  if (value is List) return Object.hashAll(value.map(_deepHash));
  if (value is Map) {
    return Object.hashAll(
      value.entries.map((e) => Object.hash(e.key, _deepHash(e.value))),
    );
  }
  return value.hashCode;
}

class Order {
  Order({
    required this.id,
    required this.petId,
    required this.quantity,
    required this.shipDate,
    required this.status,
    required this.complete,
  });

  factory Order.fromJson(Map<String, dynamic> json) {
    return Order(
      id: json['id'] != null ? (json['id'] as num).toInt() : null,
      petId: json['petId'] != null ? (json['petId'] as num).toInt() : null,
      quantity:
          json['quantity'] != null ? (json['quantity'] as num).toInt() : null,
      shipDate: json['shipDate'] as String?,
      status: json['status'] as String?,
      complete: json['complete'] as bool?,
    );
  }

  final int? id;

  final int? petId;

  final int? quantity;

  final String? shipDate;

  final String? status;

  final bool? complete;

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'petId': petId,
      'quantity': quantity,
      'shipDate': shipDate,
      'status': status,
      'complete': complete,
    };
  }

  Order copyWith({
    int? Function()? id,
    int? Function()? petId,
    int? Function()? quantity,
    String? Function()? shipDate,
    String? Function()? status,
    bool? Function()? complete,
  }) {
    return Order(
      id: id != null ? id() : this.id,
      petId: petId != null ? petId() : this.petId,
      quantity: quantity != null ? quantity() : this.quantity,
      shipDate: shipDate != null ? shipDate() : this.shipDate,
      status: status != null ? status() : this.status,
      complete: complete != null ? complete() : this.complete,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Order &&
          id == other.id &&
          petId == other.petId &&
          quantity == other.quantity &&
          shipDate == other.shipDate &&
          status == other.status &&
          complete == other.complete;

  @override
  int get hashCode =>
      Object.hash(id, petId, quantity, shipDate, status, complete);

  @override
  String toString() =>
      'Order(id: $id, petId: $petId, quantity: $quantity, shipDate: $shipDate, status: $status, complete: $complete)';
}

class Category {
  Category({
    required this.id,
    required this.name,
  });

  factory Category.fromJson(Map<String, dynamic> json) {
    return Category(
      id: json['id'] != null ? (json['id'] as num).toInt() : null,
      name: json['name'] as String?,
    );
  }

  final int? id;

  final String? name;

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'name': name,
    };
  }

  Category copyWith({
    int? Function()? id,
    String? Function()? name,
  }) {
    return Category(
      id: id != null ? id() : this.id,
      name: name != null ? name() : this.name,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Category && id == other.id && name == other.name;

  @override
  int get hashCode => Object.hash(id, name);

  @override
  String toString() => 'Category(id: $id, name: $name)';
}

class User {
  User({
    required this.id,
    required this.username,
    required this.firstName,
    required this.lastName,
    required this.email,
    required this.password,
    required this.phone,
    required this.userStatus,
  });

  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      id: json['id'] != null ? (json['id'] as num).toInt() : null,
      username: json['username'] as String?,
      firstName: json['firstName'] as String?,
      lastName: json['lastName'] as String?,
      email: json['email'] as String?,
      password: json['password'] as String?,
      phone: json['phone'] as String?,
      userStatus: json['userStatus'] != null
          ? (json['userStatus'] as num).toInt()
          : null,
    );
  }

  final int? id;

  final String? username;

  final String? firstName;

  final String? lastName;

  final String? email;

  final String? password;

  final String? phone;

  final int? userStatus;

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'username': username,
      'firstName': firstName,
      'lastName': lastName,
      'email': email,
      'password': password,
      'phone': phone,
      'userStatus': userStatus,
    };
  }

  User copyWith({
    int? Function()? id,
    String? Function()? username,
    String? Function()? firstName,
    String? Function()? lastName,
    String? Function()? email,
    String? Function()? password,
    String? Function()? phone,
    int? Function()? userStatus,
  }) {
    return User(
      id: id != null ? id() : this.id,
      username: username != null ? username() : this.username,
      firstName: firstName != null ? firstName() : this.firstName,
      lastName: lastName != null ? lastName() : this.lastName,
      email: email != null ? email() : this.email,
      password: password != null ? password() : this.password,
      phone: phone != null ? phone() : this.phone,
      userStatus: userStatus != null ? userStatus() : this.userStatus,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is User &&
          id == other.id &&
          username == other.username &&
          firstName == other.firstName &&
          lastName == other.lastName &&
          email == other.email &&
          password == other.password &&
          phone == other.phone &&
          userStatus == other.userStatus;

  @override
  int get hashCode => Object.hash(
      id, username, firstName, lastName, email, password, phone, userStatus);

  @override
  String toString() =>
      'User(id: $id, username: $username, firstName: $firstName, lastName: $lastName, email: $email, password: $password, phone: $phone, userStatus: $userStatus)';
}

class Tag {
  Tag({
    required this.id,
    required this.name,
  });

  factory Tag.fromJson(Map<String, dynamic> json) {
    return Tag(
      id: json['id'] != null ? (json['id'] as num).toInt() : null,
      name: json['name'] as String?,
    );
  }

  final int? id;

  final String? name;

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'name': name,
    };
  }

  Tag copyWith({
    int? Function()? id,
    String? Function()? name,
  }) {
    return Tag(
      id: id != null ? id() : this.id,
      name: name != null ? name() : this.name,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Tag && id == other.id && name == other.name;

  @override
  int get hashCode => Object.hash(id, name);

  @override
  String toString() => 'Tag(id: $id, name: $name)';
}

class Pet {
  Pet({
    required this.id,
    required this.name,
    required this.category,
    required this.photoUrls,
    required this.tags,
    required this.status,
  });

  factory Pet.fromJson(Map<String, dynamic> json) {
    return Pet(
      id: json['id'] != null ? (json['id'] as num).toInt() : null,
      name: json['name'] as String,
      category: json['category'] != null
          ? Category.fromJson(json['category'] as Map<String, dynamic>)
          : null,
      photoUrls:
          (json['photoUrls'] as List<dynamic>).map((e) => e as String).toList(),
      tags: json['tags'] != null
          ? (json['tags'] as List<dynamic>)
              .map((e) => Tag.fromJson(e as Map<String, dynamic>))
              .toList()
          : null,
      status: json['status'] as String?,
    );
  }

  final int? id;

  final String name;

  final Category? category;

  final List<String> photoUrls;

  final List<Tag>? tags;

  final String? status;

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'name': name,
      'category': category?.toJson(),
      'photoUrls': photoUrls,
      'tags': tags?.map((e) => e.toJson()).toList(),
      'status': status,
    };
  }

  Pet copyWith({
    int? Function()? id,
    String? name,
    Category? Function()? category,
    List<String>? photoUrls,
    List<Tag>? Function()? tags,
    String? Function()? status,
  }) {
    return Pet(
      id: id != null ? id() : this.id,
      name: name ?? this.name,
      category: category != null ? category() : this.category,
      photoUrls: photoUrls ?? this.photoUrls,
      tags: tags != null ? tags() : this.tags,
      status: status != null ? status() : this.status,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Pet &&
          id == other.id &&
          name == other.name &&
          category == other.category &&
          _deepEquals(photoUrls, other.photoUrls) &&
          _deepEquals(tags, other.tags) &&
          status == other.status;

  @override
  int get hashCode => Object.hash(
      id, name, category, _deepHash(photoUrls), _deepHash(tags), status);

  @override
  String toString() =>
      'Pet(id: $id, name: $name, category: $category, photoUrls: $photoUrls, tags: $tags, status: $status)';
}

class ApiResponse2 {
  ApiResponse2({
    required this.code,
    required this.type,
    required this.message,
  });

  factory ApiResponse2.fromJson(Map<String, dynamic> json) {
    return ApiResponse2(
      code: json['code'] != null ? (json['code'] as num).toInt() : null,
      type: json['type'] as String?,
      message: json['message'] as String?,
    );
  }

  final int? code;

  final String? type;

  final String? message;

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'code': code,
      'type': type,
      'message': message,
    };
  }

  ApiResponse2 copyWith({
    int? Function()? code,
    String? Function()? type,
    String? Function()? message,
  }) {
    return ApiResponse2(
      code: code != null ? code() : this.code,
      type: type != null ? type() : this.type,
      message: message != null ? message() : this.message,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiResponse2 &&
          code == other.code &&
          type == other.type &&
          message == other.message;

  @override
  int get hashCode => Object.hash(code, type, message);

  @override
  String toString() =>
      'ApiResponse2(code: $code, type: $type, message: $message)';
}
