// GENERATED CODE — DO NOT MODIFY BY HAND
//
// Generated by dart_open_fetch v0.1.0
// Timestamp: 2026-02-17T03:40:28.524066Z
// Source: packages/dart_open_fetch_core/test/fixtures/petstore.yaml
//
// requires: dart_open_fetch_runtime ^0.1.0

export 'models.dart';

export 'clients/pet_client.dart';
export 'clients/store_client.dart';
export 'clients/user_client.dart';
