// GENERATED CODE — DO NOT MODIFY BY HAND
//
// Generated by dart_open_fetch v0.1.0
// Timestamp: 2026-02-17T03:40:28.511834Z
// Source: packages/dart_open_fetch_core/test/fixtures/petstore.yaml
//
// requires: dart_open_fetch_runtime ^0.1.0

import 'dart:convert';

import 'package:dart_open_fetch_runtime/dart_open_fetch_runtime.dart';

import '../models.dart';

class StoreClient {
  StoreClient({
    required HttpAdapter adapter,
    List<Middleware> middleware = const [],
    this.baseUrl = 'https://petstore3.swagger.io/api/v3',
  }) : _chain = MiddlewareChain(adapter, middleware);

  final MiddlewareChain _chain;
  final String baseUrl;

  Future<ApiResponse<Map<String, dynamic>>> getInventory() async {
    final basePath = baseUrl.endsWith('/')
        ? baseUrl.substring(0, baseUrl.length - 1)
        : baseUrl;
    final url = Uri.parse('$basePath/store/inventory');
    final headers = <String, String>{};
    final request = HttpRequest(
      method: 'GET',
      url: url,
      headers: headers,
    );

    final response = await _chain.send(request);
    if (response.statusCode >= 200 && response.statusCode < 300) {
      if (response.body.isEmpty) {
        throw ApiException(
          statusCode: response.statusCode,
          body: 'Empty response body',
          headers: response.headers,
        );
      }
      final json = jsonDecode(response.body);
      return ApiResponse(
        data: Map<String, dynamic>.from(json as Map),
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    throw ApiException(
      statusCode: response.statusCode,
      body: response.body,
      headers: response.headers,
    );
  }

  Future<ApiResponse<Order>> placeOrder({
    Order? body,
  }) async {
    final basePath = baseUrl.endsWith('/')
        ? baseUrl.substring(0, baseUrl.length - 1)
        : baseUrl;
    final url = Uri.parse('$basePath/store/order');
    final headers = <String, String>{
      'Content-Type': 'application/json',
    };
    final jsonBody = body != null ? jsonEncode(body.toJson()) : null;
    final request = HttpRequest(
      method: 'POST',
      url: url,
      headers: headers,
      body: jsonBody,
    );

    final response = await _chain.send(request);
    if (response.statusCode >= 200 && response.statusCode < 300) {
      if (response.body.isEmpty) {
        throw ApiException(
          statusCode: response.statusCode,
          body: 'Empty response body',
          headers: response.headers,
        );
      }
      final json = jsonDecode(response.body);
      return ApiResponse(
        data: Order.fromJson(json as Map<String, dynamic>),
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    throw ApiException(
      statusCode: response.statusCode,
      body: response.body,
      headers: response.headers,
    );
  }

  Future<ApiResponse<Order>> getOrderById({
    required int orderId,
  }) async {
    final basePath = baseUrl.endsWith('/')
        ? baseUrl.substring(0, baseUrl.length - 1)
        : baseUrl;
    final url = Uri.parse(
        '$basePath/store/order/${Uri.encodeComponent(orderId.toString())}');
    final headers = <String, String>{};
    final request = HttpRequest(
      method: 'GET',
      url: url,
      headers: headers,
    );

    final response = await _chain.send(request);
    if (response.statusCode >= 200 && response.statusCode < 300) {
      if (response.body.isEmpty) {
        throw ApiException(
          statusCode: response.statusCode,
          body: 'Empty response body',
          headers: response.headers,
        );
      }
      final json = jsonDecode(response.body);
      return ApiResponse(
        data: Order.fromJson(json as Map<String, dynamic>),
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    throw ApiException(
      statusCode: response.statusCode,
      body: response.body,
      headers: response.headers,
    );
  }

  Future<HttpResponse> deleteOrder({
    required int orderId,
  }) async {
    final basePath = baseUrl.endsWith('/')
        ? baseUrl.substring(0, baseUrl.length - 1)
        : baseUrl;
    final url = Uri.parse(
        '$basePath/store/order/${Uri.encodeComponent(orderId.toString())}');
    final headers = <String, String>{};
    final request = HttpRequest(
      method: 'DELETE',
      url: url,
      headers: headers,
    );

    final response = await _chain.send(request);
    return response;
  }
}
