import 'dart:io';

import 'package:dart_style/dart_style.dart';
import 'package:pub_semver/pub_semver.dart';

import 'name_resolver.dart';

/// Coordinates writing generated code files to the output directory.
///
/// Output structure:
/// ```
/// {output}/
///   models.dart    — all model classes, enums, and union sealed classes
///   clients/       — HTTP client classes
///   {package}.dart — barrel export file
/// ```
class OutputWriter {
  OutputWriter({
    required this.outputDir,
    required this.nameResolver,
    this.schemaSource,
    this.toolVersion = '0.1.0',
    this.packageName,
  });

  final String outputDir;
  final NameResolver nameResolver;
  final String? schemaSource;
  final String toolVersion;

  /// Dart package name for `package:` imports.
  /// When set and output dir is inside `lib/`, client imports use
  /// `package:` style instead of relative `../` style.
  final String? packageName;

  final List<String> _writtenFiles = [];
  final _formatter = DartFormatter(languageVersion: Version(3, 5, 0));

  /// All files written so far.
  List<String> get writtenFiles => List.unmodifiable(_writtenFiles);

  /// Write all models into a single models.dart file.
  Future<String> writeModels(String combinedSource) async {
    final path = '$outputDir/models.dart';
    final headerSource = addHeader(combinedSource);
    await _writeFile(path, headerSource);
    return path;
  }

  /// Write a client file (clients/{name}.dart).
  ///
  /// [modelsFileName] — the models file name (e.g., `models.dart`) for the
  /// relative import `../{modelsFileName}`.
  Future<String> writeClient(
    String className,
    String source, {
    String? modelsFileName,
  }) async {
    final withImports = modelsFileName != null
        ? _injectModelsImport(source, modelsFileName)
        : source;

    final fileName = nameResolver.resolveFileName(className);
    final path = '$outputDir/clients/$fileName';
    await _writeFile(path, withImports);
    return path;
  }

  /// Write the barrel export file.
  Future<String> writeBarrel(
    String packageName,
    String? modelsFileName,
    List<String> clientFileNames,
  ) async {
    final buf = StringBuffer();
    buf.writeln(_generationHeader());
    buf.writeln();

    if (modelsFileName != null) {
      buf.writeln("export '$modelsFileName';");
    }

    if (clientFileNames.isNotEmpty) {
      buf.writeln();
      for (final client in clientFileNames..sort()) {
        buf.writeln("export 'clients/$client';");
      }
    }

    final path = '$outputDir/$packageName.dart';
    await _writeFile(path, buf.toString());
    return path;
  }

  String _generationHeader() {
    final timestamp = DateTime.now().toUtc().toIso8601String();
    final source = schemaSource != null ? '\n// Source: $schemaSource' : '';
    return '// GENERATED CODE — DO NOT MODIFY BY HAND\n'
        '//\n'
        '// Generated by dart_open_fetch v$toolVersion\n'
        '// Timestamp: $timestamp$source\n'
        '//\n'
        '// requires: dart_open_fetch_runtime ^0.1.0';
  }

  /// Add the generation header to a source string.
  String addHeader(String source) {
    return '${_generationHeader()}\n\n$source';
  }

  /// Inject a models import into client source code.
  String _injectModelsImport(String source, String modelsFileName) {
    final importLine = _modelsImportLine(modelsFileName);

    // Insert after the last existing import statement
    final lastImportMatch =
        RegExp(r"^import\s.*;\s*$", multiLine: true).allMatches(source);
    if (lastImportMatch.isNotEmpty) {
      final lastMatch = lastImportMatch.last;
      final endOfLine = source.indexOf('\n', lastMatch.end);
      if (endOfLine >= 0) {
        return '${source.substring(0, endOfLine + 1)}$importLine\n${source.substring(endOfLine + 1)}';
      }
    }

    return '$importLine\n$source';
  }

  /// Build the import line for models.
  ///
  /// Uses `package:` import when [packageName] is set and [outputDir]
  /// is inside a `lib/` directory. Falls back to relative import.
  String _modelsImportLine(String modelsFileName) {
    if (packageName != null) {
      final libIndex = outputDir.indexOf('lib/');
      if (libIndex >= 0) {
        final relativeFromLib = outputDir.substring(libIndex + 4);
        return "import 'package:$packageName/$relativeFromLib/$modelsFileName';";
      }
    }
    return "import '../$modelsFileName';";
  }

  Future<void> _writeFile(String path, String content) async {
    final file = File(path);
    await file.parent.create(recursive: true);

    String formatted;
    try {
      formatted = _formatter.format(content);
    } catch (_) {
      formatted = content;
    }

    await file.writeAsString(formatted);
    _writtenFiles.add(path);
  }
}
